# install security configuration
- name: ensure python packages are installed
  apt:
    name: [ 'python3-pip', 'python3-dev', 'fail2ban' ]
    update_cache: yes
  become: yes

- name: unable ssh within the firewall
  ufw: rule=allow port=22
  become: yes

- name: enable the firewall
  ufw: state=enabled
  become: yes